image: node:latest

stages:
  - build
  - deploy

.setup:
  before_script:
    - apt-get update && apt-get -y install rsync jq moreutils
    - yarn

build:
  stage: build
  extends: .setup
  script:
    - yarn clean
    - yarn build
  artifacts:
    paths:
      - build/

deploy:
  stage: deploy
  extends: .setup
  needs:
    - build
  script:
    - jq '.name = "@one-am/expo-play-asset-delivery"' package.json | sponge package.json
    - echo "@one-am:registry=https://git.oneam.it/api/v4/projects/${CI_PROJECT_ID}/packages/npm/" > .npmrc
    - echo "//git.oneam.it/api/v4/projects/${CI_PROJECT_ID}/packages/npm/:_authToken=${CI_JOB_TOKEN}" >> .npmrc
    - npm publish
  only:
    - tags